# Generated by Django 4.2.27 on 2026-01-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('provincia', models.CharField(db_column='Provincia', max_length=100)),
                ('canton', models.CharField(db_column='Canton', max_length=100)),
                ('distrito', models.CharField(db_column='Distrito', max_length=100)),
                ('codigopostal', models.CharField(blank=True, db_column='CodigoPostal', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('creadoen', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
            ],
            options={
                'db_table': 'Direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('contacto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Contacto', max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Email', max_length=100, unique=True)),
                ('passwordhash', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='PasswordHash', max_length=255)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=20, null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
                ('creadoen', models.DateTimeField(blank=True, db_column='CreadoEn', null=True)),
                ('username', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Username', max_length=150, null=True, unique=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('issuperuser', models.BooleanField(blank=True, db_column='IsSuperuser', null=True)),
                ('isstaff', models.BooleanField(blank=True, db_column='IsStaff', null=True)),
                ('direccionid', models.ForeignKey(blank=True, db_column='DireccionId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.direcciones')),
                ('rolid', models.ForeignKey(db_column='RolId', on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.roles')),
            ],
        ),
    ]
