# Generated by Django 4.2.27 on 2026-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelosMotor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('especificaciones', models.TextField(blank=True, db_column='Especificaciones', null=True)),
            ],
            options={
                'verbose_name': 'Modelo de Motor',
                'verbose_name_plural': 'Modelos de Motor',
                'db_table': 'ModelosMotor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numeroserie', models.CharField(blank=True, db_column='NumeroSerie', max_length=100, null=True)),
                ('creadoen', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
                'db_table': 'Motores',
                'ordering': ['-creadoen'],
                'managed': False,
            },
        ),
    ]
