# Generated by Django 4.2.27 on 2026-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=50, null=True)),
                ('stock', models.IntegerField(db_column='Stock', default=0)),
                ('stockminimo', models.IntegerField(db_column='StockMinimo', default=0)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
    ]
