# Generated by Django 4.2.27 on 2026-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('creadoen', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
                ('username', models.CharField(blank=True, db_column='Username', max_length=150, null=True, unique=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('issuperuser', models.BooleanField(db_column='IsSuperuser', default=False)),
                ('isstaff', models.BooleanField(db_column='IsStaff', default=False)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('provincia', models.CharField(db_column='Provincia', max_length=100)),
                ('canton', models.CharField(db_column='Canton', max_length=100)),
                ('distrito', models.CharField(db_column='Distrito', max_length=100)),
                ('codigopostal', models.CharField(blank=True, db_column='CodigoPostal', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('creadoen', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
            ],
            options={
                'db_table': 'Direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
    ]
