# Generated by Django 4.2.27 on 2026-02-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
