# Generated by Django 4.2.27 on 2026-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticosTecnicos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('detalle', models.TextField(db_column='Detalle')),
                ('creadoen', models.DateTimeField(auto_now_add=True, db_column='CreadoEn')),
            ],
            options={
                'db_table': 'DiagnosticosTecnicos',
                'ordering': ['-creadoen'],
                'managed': False,
            },
        ),
    ]
